customer_info/urls.py
from django.urls import path
from customer_info import views
from django.contrib.auth.models import User

app_name = 'customer_info'


urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('user_login', views.user_login,name='user_login'),
    path('payment',views.PaymentListView.as_view(),name='payment'),
    path('detail/<int:pk>/',views.CustomerDetailView.as_view(),name='detail'),
    path('register', views.register,name='register')
]

customers_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from customer_info import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer_info/',include('customer_info.urls')),
    path('',views.IndexView.as_view(),name='index'),
    path('logout/',views.user_logout,name='logout')
]

customer_info/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.IntegerField(primary_key=True)


    def __str__(self):
        return self.user.username


    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         UserProfileInfo.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.userprofileinfo.save()


class Customer(models.Model):
    full_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=6)
    home_address = models.CharField(max_length=50)
    office_address = models.CharField(max_length=50)
    phone_number = models.IntegerField(primary_key=True)
    email = models.EmailField(max_length=30)
    next_of_kin = models.CharField(max_length=30)
    relationship = models.CharField(max_length=20)
    estate = models.CharField(max_length=30)
    plots = models.IntegerField()
    amount = models.IntegerField()
    amount_paid = models.IntegerField()
    balance = models.IntegerField()
    registration_date = models.DateField()
    payment_complete = models.BooleanField(default=False)
    documentation = models.BooleanField(default=False)

    def __str__(self):
        return self.full_name


class Account_detail(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    amount_paid = models.IntegerField()
    date = models.DateField()
    reciept_number = models.IntegerField()
    balance = models.IntegerField()


    def __str__(self):
        return str(self.name)

customer_info/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','first_name','last_name','password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = models.UserProfileInfo
        fields = ('phone_number',)

customer_info/views.py
from django.shortcuts import render
from customer_info.models import Customer, Account_detail
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from . import models
from . import forms

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
class IndexView(TemplateView):
    template_name = 'customer_info/index.html'


class CustomerDetailView(DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['max_value'] = 100
        return context


class PaymentListView(ListView):
    model = Account_detail
    
    def get_queryset(self):
        queryset = Account_detail.objects.filter(customer__full_name='{} {}'.format(self.request.user.first_name,
                                                                                            self.request.user.last_name).upper())
        return queryset




def register(request):
    registered = False
    user_form = forms.UserForm()
    profile_form = forms.UserProfileForm()

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileForm(data=request.POST)
        if user_form.is_valid:
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'phone_number' in request.POST:
                profile.phone_number = request.POST['phone_number']
                profile.save()

            registered = True
            return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors)

    else:
        return render(request,'customer_info/registration.html',{'user_form':user_form,
                                                            'profile_form':profile_form,
                                                            'registered':registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to log in and failed')
            return HttpResponse('Invalid login details')
    else:
        return render(request, 'customer_info/user_login.html')

templates/customer_info/account_detail_list.html
{% extends 'customer_info/base.html' %}
{% load humanize %}
{% block content %}
  <div class="container">
      <h1>PAYMENT DETAILS</h1>
      <!-- {% if customer.balance == 0 %}
        <div class="alert alert-success" role="alert">
          Completed payment
        </div>
      {% else %}
        <div class="alert alert-warning" role="alert">
          <h5><strong>NOTE:</strong> You Have {{customer.registration_date|timesince}} to complete your payment</h5>
        </div>
      {% endif %} -->
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">FULL NAME</th>
              <th scope="col">AMOUNT</th>
              <th scope="col">DATE</th>
              <th scope="col">RECIEPT NUMBER</th>
              <th scope="col">BALANCE</th>
            </tr>
          </thead>
          <tbody>
            {% for record in account_detail_list %}
              <tr>
                <td>{{record.customer}}</td>
                <td>{{record.amount_paid  | intcomma }}</td>
                <td>{{record.date}}</td>
                <td>000{{record.reciept_number}}</td>
                <td>{{record.balance  | intcomma }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
          <a class="btn btn-primary" type="button" style='padding:5px' href="{% url 'customer_info:detail' user.userprofileinfo.phone_number %}">PROFILE</a>
  </div>
{% endblock%}

templates/customer_info/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title></title>
  </head>
  <body>
    <div>
      <nav class="navbar sticky-top navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand " id="mybrand" href="{% url 'customer_info:index' %}">BASHMOH HOMES</a>
          <ul class="nav nav-pills">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer_info:detail' user.userprofileinfo.phone_number %}">Profile</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link "  href="{% url 'customer_info:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'customer_info:user_login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/customer_info/customer_detail.html
{% extends 'customer_info/base.html' %}
{% load humanize %}
{% block content%}
<div class="container"  style='width:60%'>
    <h2>{{customer.full_name}}</h2>
    <small>PAYMENT:</small>
    <div class="progress">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar"
        style="width:{% widthratio customer.amount_paid customer.amount max_value %}%" aria-valuenow="25"
        aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <small>DOCUMENTATION:</small>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 0%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <hr>
  {% if customer.balance == 0 %}
    <div class="alert alert-success" role="alert">
      Completed payment
    </div>
  {% else %}
    <div class="alert alert-warning" role="alert">
      <h5><strong>NOTE:</strong> You Have {{customer.registration_date|timesince}} to complete your payment</h5>
    </div>
  {% endif %}
  <div class="container">
    <h5 style='padding:10px'><strong>HOME ADDRESS:</strong> <em style='font-family:verdana'>{{customer.home_address}}</em></h5>
    <h5 style='padding:10px'><strong>OFFICE ADDRESS:</strong> <em style='font-family:verdana'>{{customer.office_address}}</em></h5>
    <h5 style='padding:10px'><strong>TELEPHONE:</strong> <em style='font-family:verdana'>{{customer.phone_number}}</em></h5>
    <h5 style='padding:10px'><strong>EMAIL:</strong> <em style='font-family:verdana'>{{customer.email}}</em></h5>
    <h5 style='padding:10px'><strong>NEXT OF KIN:</strong> <em style='font-family:verdana'>{{customer.next_of_kin}}</em></h5>
    <h5 style='padding:10px'><strong>RELATIONSHIP:</strong> <em style='font-family:verdana'>{{customer.relationship}}</em></h5>
  </div>
  <hr>
  <div class="container">
    <h5 style='padding:10px'><strong>ESTATE:</strong> <em style='font-family:verdana'>{{customer.estate}}</em></h5>
    <h5 style='padding:10px'><strong>NUMBER OF PLOTS:</strong> <em style='font-family:verdana'>{{customer.plots}}</em></h5>
    <h5 style='padding:10px'><strong>AMOUNT:</strong>N <em style='font-family:verdana'>{{customer.amount | intcomma }}</em></h5>
    <h5 style='padding:10px'><strong>AMOUNT PAID:</strong>N <em style='font-family:verdana'>{{customer.amount_paid | intcomma }}</em></h5>
    <h5 style='padding:10px'><strong>BALANCE:</strong>N <em style='font-family:verdana'>{{customer.balance | intcomma }}</em></h5>
  </div>
  <a class="btn btn-info" type="button" style='padding:10px' href="{% url 'customer_info:payment' %}">PAYMENT DETAILS</a>
</div>
{% endblock %}

templates/customer_info/index.html
{% extends 'customer_info/base.html' %}

{% block content %}
    <div class="mydiv container">

      <div class="card">
          <img src="" alt="" class="card__img">
          <div class="card__body">
              <h3 class="card__title">BASHMOH HOMES</h3>
              <p class='card__text'><em>...Providing housing for all.</em></p>
          </div>
        </div>
        <hr>
        <div class="container">
          <div class="d-grid gap-2 col-6 mx-auto" id="submit">
            <a class="btn btn-success btn-lg" type="button" href="">CHECK YOUR ACCOUNT STATUS</a>
          </div>
      </div>
    </div>
{% endblock %}

templates/customer_info/payment_details.html
{% block content %}
  <div class="container">
      <h1>CUSTOMER LIST</h1>
          <table class="table table-dark table-striped">
            <thead>
              <tr>
                <th scope="col">FULL NAME</th>
                <th scope="col">AMOUNT</th>
                <th scope="col">ESTATE</th>
              </tr>
            </thead>
            <tbody>
              {% for customer in customers %}
                <tr>
                  <td>{{customer.full_name}}</td>
                  <td>{{customer.amount}}</td>
                  <td>{{customer.estate}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>        
  </div>

{% endblock%}

templates/customer_info/registration.html
{% extends 'customer_info/base.html' %}

{% block content %}

  <div class="container">
      {% if registered %}
        <h1>THANKS YOU!</h1>
      {% else %}
      <div class="container" id="main">
        <h1>Register Here</h1>
          <form class=""  method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input class="" type="submit" name="" value="Register">
          </form>
      </div>
      {% endif %}
    </div>
{% endblock %}

templates/customer_info/user_login.html
{% extends 'customer_info/base.html' %}

  {% block content %}
  <div class="container" style="margin-top:40px; width:50%">
    <form class="" action="{% url 'customer_info:user_login' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="username" class="form-label"><strong>Username</strong></label>
        <input type="text" class="form-control" name="username" placeholder="laide">
      </div>
      <div class="mb-3">
        <label for="password" class="form-label"><strong>Password</strong></label>
        <input type="password" class="form-control" name="password" placeholder="******">
      </div>
      <div class="mb-3">
        <input type="Submit" class="form-control btn btn-primary" id="FormControlInput2" value="Log In">
      </div>
    </form>
  </div>
  {% endblock %}